config/routes.rb
Rails.application.routes.draw do
  
  match 'message_stuff', :to => 'messages#message_stuff', via: 'get'
  match 'message_get', :to => 'messages#message_get_ajax', via: 'get'
  match 'message_change', :to => 'messages#message_change_ajax', via: 'get'
  match 'message_recovery', :to => 'messages#message_recovery_ajax', via: 'get'

  get 'republics/list'
  match 'repuplic_information', :to => 'republics#repuplic_information_ajax', via: 'get'
  match 'update_republic', :to => 'republics#update_republic_ajax', via: 'get'
  match 'upload_image', :to => 'republics#upload_image_ajax', via: 'post'
  match 'delete_image', :to => 'republics#delete_image_ajax', via: 'get'
  match 'filter_republics', :to => 'republics#filter_republics_ajax', via: 'get'
  match 'increment_phone_views',  :to => 'republics#increment_phone_views_ajax', via: 'get'
  match 'phone_views_number',  :to => 'republics#phone_views_number', via: 'get'

  match 'signup', :to => 'users#new', via: 'post'
  match 'signup_user', :to => 'users#new_ajax', via: 'post'
  match 'new_republic', :to => 'users#new_republic', via: 'post'
  match 'user_home', :to => 'users#home', via: 'get'
  match 'user_edit', :to => 'users#edit', via: 'patch'
  match 'user_edit_password', :to => 'users#edit_password', via: 'patch'
  match 'user_change_password', :to => 'users#update_password', via: 'patch'
  match 'recovery_password', :to => 'users#recovery_password_ajax', via: 'get'
  match 'delete_announce', :to => 'users#delete_announce_ajax', via: 'get'
  match 'teste', :to => 'users#teste', via: 'get'
  match 'team', :to => 'users#team', via: 'get'
  match 'change_password',  :to => 'users#change_password', via: 'get'

  root :to => 'web_sites#index'
  match 'index', :to => 'web_sites#index', via: 'get'
  match 'register_people', :to => 'web_sites#register_people', via: 'get'
  match 'register_vacancy', :to => 'web_sites#register_vacancy', via: 'get'
  match 'register_property', :to => 'web_sites#register_property', via: 'get'
  match 'search_people', :to => 'web_sites#search_people', via: 'get'
  match 'search_filter', :to => 'web_sites#search_filter', via: 'get'
  match 'search', :to => 'web_sites#search', via: 'get'
  match 'send_message', :to => 'web_sites#new_message', via: 'get'
  match 'send_message_thiago', :to => 'messages#send_message_thiago_ajax', via: 'get'
  match 'send_message_for_user', :to => 'messages#message_for_user_ajax', via: 'get'
  match 'send_message_for_friend', :to => 'messages#message_for_friend_ajax', via: 'get'
  match 'save_maps',  :to => 'web_sites#save_maps_ajax', via: 'get'
  match 'activate',  :to => 'web_sites#activate_ajax', via: 'get'
  match 'update_coordinates',  :to => 'web_sites#update_coordinates_ajax', via: 'get'
  match 'listing_preview',  :to => 'web_sites#listing_preview', via: 'get'
  match 'change_lang',  :to => 'web_sites#change_lang', via: 'get'
  match 'enable',  :to => 'web_sites#enable', via: 'get'
  match 'enable_delete',  :to => 'web_sites#enable_delete_ajax', via: 'get'
  match 'maps',  :to => 'web_sites#maps', via: 'get'
  match 'email_user',  :to => 'web_sites#email_user', via: 'get'
  
  match 'partners_help',  :to => 'web_sites#partners_help', via: 'get'
  match 'new_partner', :to => 'web_sites#new_partner_ajax', via: 'post'
  match 'partner_info',  :to => 'web_sites#partner_info_ajax', via: 'get'
  match 'update_partner',  :to => 'web_sites#update_partner_ajax', via: 'post'
  match 'partners',  :to => 'web_sites#partners', via: 'get'
  
  match 'university_help',  :to => 'web_sites#university_help', via: 'get'
  match 'new_university', :to => 'web_sites#new_university_ajax', via: 'post'
  match 'university_info',  :to => 'web_sites#university_info_ajax', via: 'get'
  match 'update_university',  :to => 'web_sites#update_university_ajax', via: 'post'
  match 'set_system_university',  :to => 'web_sites#set_system_university_ajax', via: 'get'
  
  match 'questions_help',  :to => 'web_sites#questions_help', via: 'get'
  match 'university_questions',  :to => 'web_sites#university_questions_ajax', via: 'get'
  match 'new_question', :to => 'web_sites#new_question_ajax', via: 'post'
  match 'question_answers', :to => 'web_sites#question_answers_ajax', via: 'get'
  match 'update_question', :to => 'web_sites#update_question_ajax', via: 'post'
  match 'update_answer', :to => 'web_sites#update_answer_ajax', via: 'get'
  
  match 'answer_compatibility_process', :to => 'web_sites#answer_compatibility_process_ajax', via: 'get'
  match 'quick_answer', :to => 'web_sites#quick_answer_ajax', via: 'get'
  match 'reset_questions', :to => 'web_sites#reset_questions_ajax', via: 'get'
  
  match 'thiago_melo_resume_pt',  :to => 'web_sites#thiago_melo_resume_pt', via: 'get'
  match 'thiago_melo_resume_en',  :to => 'web_sites#thiago_melo_resume_en', via: 'get'
  
  
  
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  match 'login_facebook',  :to => 'sessions#login_facebook', via: 'post'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :active, :inclusion => {:in => [true, false]}
  validates :premium, :inclusion => {:in => [true, false]}
  validates :admin, :inclusion => {:in => [true, false]}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :password, length: {minimum: 6}, on: :update, allow_blank: true
  
  has_many :user_answers, dependent: :destroy
  has_many :answers, through: :user_answers
  has_many :questions, through: :user_answers
  
  has_many :republics, dependent: :destroy
  has_many :password_recoveries, dependent: :destroy
  
  def create_adjusts
    self.active = 1
    self.premium = 0
    self.admin = 0
    if self.last_name.include? "'"
      self.username = self.first_name.downcase + "_" + self.last_name.downcase.gsub("'","")
    else
      self.username = self.first_name.downcase + "_" + self.last_name.downcase
    end
    if self.username.include? " "
      self.username = self.username.gsub(" ","_")
    end
    if self.username.include? "-"
      self.username = self.username.gsub("-","_")
    end
    if self.username.include? "."
      self.username = self.username.gsub(".","")
    end
    id = 0
    username = self.username
    while User.where("username = '#{self.username}'").length > 0 do
      self.username = "#{username}_#{id}"        
      id += 1
    end
  end
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def clean_for_ajax
    return self.slice(:id, :first_name, :last_name, :hide_email, :phone, :hide_phone, :email, :facebook)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'net/smtp'
  
  def new
    user = User.new(user_params)
    user.create_adjusts
    if user.save
      log_in user
      welcome_message user.first_name, user.email
      case params[:announce_type]
        when "property"
          redirect_to register_property_path
        when "people"
          redirect_to register_people_path
        when "vacancy"
          redirect_to register_vacancy_path
      end
    else
      flash[:danger] = getTextMessage("signup_error_message")
      redirect_to root_path
    end
  end
  
  def new_republic
    if !logged_in?
      redirect_to root_path
    end
    user = current_user
    republic = Republic.new(republic_params)
    republic.user_id = user.id
    republic.active = true
    if republic.save
      if params[:pictures]
        params[:pictures].each do |image|
          picture = Picture.new
          picture.main = 0
          picture.path = "temp"
          picture.republic_id = republic.id
          if picture.save
            picture.path = save_image_to_s3(image, "pictures", "#{picture.republic_id}_#{picture.id}")
            picture.save
          else
            flash[:danger] = getTextMessage("fail_vacancy_registration")
          end
        end
      end
      message_republic_registered user.first_name, user.email
      flash[:success] = getTextMessage("success_vacancy_registration")
	    redirect_to user_home_path
	  else
      flash[:danger] = getTextMessage("fail_vacancy_registration")
      redirect_to root_path
    end
  end
  
  def home
    if !logged_in?
      redirect_to root_path
    end
    if current_user.admin
      redirect_to team_path
    end
    
    questions = Question.where("language = ?", systemLanguage)
    questions_number = questions.length
    questions_answered = 0
    user_answers = current_user.user_answers
    
    user_answers.each do |answer|
      question = answer.question
      if question.language == systemLanguage
        questions_answered += 1
      end
    end
    
    @compatibility_complete = questions_answered == questions_number
  end
  
  def team
    #if logged_in? and !current_user.admin
      @new_republics = Republic.where(latitude: nil)
      @edit_republics = Republic.all
      @messages = Message.all.order(created_at: :desc)
    #else
    #  redirect_to root_path
    #end
  end
  
  def edit
    if !logged_in?
      redirect_to root_path
    end
    if current_user.update_attributes(user_edit_params)
      flash[:success] = getTextMessage("user_alteration_success")
    else
      flash[:danger] = getTextMessage("user_alteration_fail")
    end
    redirect_to user_home_path
  end
  
  def edit_password
    if !logged_in?
      redirect_to root_path
    end
    if current_user.authenticate(params[:user][:password_old])
      if current_user.update_attributes(user_edit_password_params)
        flash[:success] = getTextMessage("password_changed_successfully")
      else
        flash[:danger] = getTextMessage("password_changed_fail")
      end
    else
      flash[:danger] = getTextMessage("invalid_old_password")
    end
    redirect_to user_home_path
  end
  
  def teste
    send_email "thiago.lc.melo@gmail.com", "um teste", signature
  end
  
  def change_password
    if !logged_in?
      user = User.find_by(email: params[:email])
      if !user.nil?
        passrecovery = PasswordRecovery.find(params[:code])
        if passrecovery.user_id == user.id and !passrecovery.used
          #passrecovery.used = true
          #passrecovery.save
          @user = user
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
  
  def update_password
    if logged_in?
      redirect_to root_path
    end
    user = User.find(params[:user][:id])
    if !user.nil?
      passrecovery = PasswordRecovery.where(user_id: user.id).where(used: false).take
      if !passrecovery.nil?
        if user.update_attributes(user_edit_password_params)
          passrecovery.used = true
          passrecovery.save
          log_in user
          remember(user)
          redirect_to user_home_path
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
  
  # ajax methods
  
  def recovery_password_ajax
    if logged_in?
      flash[:danger] = getTextMessage("disconected_for_security")
      log_out
      redirect_to root_url
      return
    end
    user = User.find_by(email: params[:recovery_email].downcase)
    if !user.nil?
      passrecovery = PasswordRecovery.where(user_id: user.id).where(used: false).take
      if passrecovery.nil?
        passrecovery = PasswordRecovery.new(user_id: user.id, used: false)
        passrecovery.save
      end
      password_recovery_message user.first_name, user.email, passrecovery.id
      container = { "status" => "success" }
    else
      container = { "status" => "fail" }
    end
    render :json => container.to_json
  end
  
  def delete_announce_ajax
    if !logged_in?
      redirect_to root_url
      return
    end
    republic = Republic.find(params[:id])
    if !republic.nil?
      if republic.user.id == current_user.id
        republic.active = false
        if republic.save
          container = { "status" => "success" }
        else
          container = { "status" => "fail" }
        end
      else
        flash[:danger] = getTextMessage("disconected_for_security")
        log_out
        redirect_to root_url
        return
      end
    else
      container = { "status" => "fail" }
    end
    render :json => container.to_json
  end
  
  # this should perform the signup for a user through normal way
  # using ajax request
  def new_ajax
    user = User.new(user_params)
    user.create_adjusts
    if user.save
      log_in user
      welcome_message user.first_name, user.email
      container = { "status" => "success" }
    else
      container = { "status" => "fail" }
    end
    render :json => container.to_json
  end
  
  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :hide_email, :password,
        :password_confirmation, :facebook, :phone, :hide_phone)
    end
    
    def user_edit_params
      params.require(:user).permit(:first_name, :last_name, :hide_email, :email, :facebook, :phone, :hide_phone)
    end
    
    def user_edit_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    
    def republic_params
      params.require(:republic).permit(:title, :is_people, :is_landlord, :address, :number, :shape, 
        :hide_address, :gender, :cost, :roommates, :description, :pets, :smoking, :alcohol,
        :stuff, :bathrooms, :heating, :parking, :parties, :organization, :lease, :university_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password.html.erb
    <% provide(:title, "Change password") %>
		
		<div class="container" id="homepage">
		  <%= form_for(@user, url: user_change_password_path, onSubmit: "return validateChangePassword()") do |f| %>
		    <%= f.hidden_field :id, :value => @user.id %>
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<div class="page-header">
						  <h3 class="text-center"><i class="fa fa-lock text-danger"></i> <%= getTextMessage("change_password") %></h3>
						</div>
						<div class="row">
							<div class="col-md-12">
								<div id="change_password_message"></div>
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-md-6 col-md-offset-3">
								<i class="fa fa-lock"></i> <%= f.label :password, getTextMessage("new_password") %> <i class="fa fa-asterisk text-danger"></i>
								<%= f.password_field :password, class: "form-control", placeholder: getTextMessage("new_password") %>
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-md-6 col-md-offset-3">
								<i class="fa fa-lock"></i> <%= f.label :password_confirmation, getTextMessage("confirm_password") %> <i class="fa fa-asterisk text-danger"></i>
								<%= f.password_field :password_confirmation, class: "form-control", placeholder: getTextMessage("confirm_password") %>
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-md-12 col-md-offset-0" align="center">
								<%= f.submit getTextMessage("change"), class: "btn btn-danger", onclick: "return validateChangePassword()" %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>

app/views/users/home.html.erb
<% provide(:title, "Home") %>
		
		<div class="container" id="homepage">
			<br>
			<% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>" role="alert">
          	<strong><%= value %></strong>
						<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          </div>
      <% end %>
			<div class="page-header">
			  <h2><%= getTextMessage("hello") %> <%= current_user.first_name %>! <a id="compatibility_research_button_home" href="javascript: launcher = 'home'; launchCompatibilityDialog();" class="btn btn-info btn-lg pull-right"><% if !@compatibility_complete %><i class="fa fa-star fa-spin"><i class="fa fa-star-o fa-spin"></i></i> <%= getTextMessage("compatibility_research") %> <i class="fa fa-star-o fa-spin"><i class="fa fa-star fa-spin"></i></i><% else %><%= getTextMessage("compatibility_research") %><% end %></a></h2>
			</div>
			<ul class="nav nav-tabs" role="tablist">
			  <li class="active"><a href="#republics" role="tab" data-toggle="tab"><i class="fa fa-home"></i> <%= getTextMessage("announced_vacancy") %> </a></li>
			  <li><a href="#contact" role="tab" data-toggle="tab"><i class="fa fa-cog"></i> <%= getTextMessage("settings") %></a></li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content">
			  <div class="tab-pane fade in active" id="republics">
			  	<% if current_user.republics.where(active: true).length > 0 %>
			  		<div class="row">
							<div class="col-md-4 col-md-offset-0">
								<br>
								<table class="table table-hover table-bordered">
									<thread>
										<tr>
											<th><%= getTextMessage("your_vacancies") %></th>
										</tr>
									</thread>
									<tbody>
										<% current_user.republics.each do |rep| %>
											<% if rep.active %>
												<tr>
													<td><a href="javascript: republic_content_builder(<%= rep.id %>);" id="title_link_<%= rep.id %>"><%= rep.title %><b><%= " | " + getTextMessage("home_add_pictures") + "!" if rep.pictures.length == 0 %></b></a></td>
												</tr>
											<% end %>
										<% end %>
										<tr>
											<td>
												<!-- <a href="javascript: republic_content_builder(0);"><i class="fa fa-plus"></i> Adicionar outra <b>(Em breve)</b></a> -->
												<a href="#" data-toggle="modal" data-target="#announce_type" ><i class="fa fa-plus"></i> <%= getTextMessage("add_other") %></a>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
							<div class="col-md-8 col-md-offset-0">
								<div id="republic_content"></div>
							</div>
						</div>
					<% else %>
						<br><br>
						<p class="lead" align="center"><%= getTextMessage("no_vacancies") %> <i class="fa fa-frown-o"></i></p>
						<p align="center"><a href="#" data-toggle="modal" data-target="#announce_type" class="btn btn-success"><i class="fa fa-smile-o"></i> <%= getTextMessage("register_now") %>!</a></p>
					<% end %>
			  </div>
			  <div class="tab-pane fade" id="contact">
			  	<br>
			  	<ul class="nav nav-pills" role="tablist">
					  <li class="active"><a href="#info_data" role="tab" data-toggle="tab"><i class="fa fa-user"></i> <%= getTextMessage("your_data") %></a></li>
					  <li><a href="#change_password" role="tab" data-toggle="tab"><i class="fa fa-lock"></i> <%= getTextMessage("change_password") %></a></li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content">
					  <div class="tab-pane active" id="info_data">
					  	<%= form_for(current_user, url: user_edit_path, onSubmit: "return validateEdit()") do |f| %>
								<div class="row">
									<div class="col-md-6 col-md-offset-3">
										<div class="page-header">
										  <h3 class="text-center"><%= getTextMessage("contact_data") %> <small>(<%= getTextMessage("required_fields") %> <i class="fa fa-asterisk text-danger"></i>)</small></h3>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div id="edit_user_message"></div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-6 col-md-offset-0">
												<i class="fa fa-chevron-right"></i> <%= f.label :first_name, getTextMessage("name") %> <i class="fa fa-asterisk text-danger"></i>
												<%= f.text_field :first_name, class: "form-control", placeholder: getTextMessage("name") %>
											</div>
											<div class="col-md-6 col-md-offset-0">
												<i class="fa fa-chevron-right"></i> <%= f.label :last_name, getTextMessage("surname") %> <i class="fa fa-asterisk text-danger"></i>
												<%= f.text_field :last_name, class: "form-control", placeholder: getTextMessage("surname") %>
											</div>
										</div>
										<br>
										<div class="row">
											<div class="col-md-12 col-md-offset-0">
											  <i class="fa fa-facebook-official"></i> <%= f.label :facebook, placeholder: getTextMessage("facebook") %>
												<%= f.text_field :facebook, class: "form-control", placeholder: getTextMessage("facebook") %>
											</div>
										</div>
										<br>
										<div class="row">
											<div class="col-md-6 col-md-offset-0">
												<i class="fa fa-inbox"></i> <%= f.label :email %> <i class="fa fa-asterisk text-danger"></i>
												<div class="pull-right"><%= f.check_box :hide_email %> <%= f.label :hide_email, getTextMessage("hide") %> <b><span data-toggle="tooltip" data-placement="top" title="<%= getTextMessage("hide_explanation") %>">[?]</span></b></div>
												<%= f.text_field :email, class: "form-control", placeholder: getTextMessage("email") %>
											</div>
											<div class="col-md-6 col-md-offset-0">
												<i class="fa fa-phone"></i> <%= f.label :phone %>
												<div class="pull-right"><%= f.check_box :hide_phone %> <%= f.label :hide_phone, getTextMessage("hide") %></div>
												<%= f.text_field :phone, class: "form-control", placeholder: getTextMessage("phone") %>
											</div>
										</div>
										<br>
										<div class="row">
											<div class="col-md-12 col-md-offset-0" align="center">
												<%= f.submit getTextMessage("change"), class: "btn btn-danger", onclick: "return validateEdit()" %>
											</div>
										</div>
									</div>
								</div>
							<% end %>
					  </div>
					  <div class="tab-pane" id="change_password">
					  	<%= form_for(current_user, url: user_edit_password_path, onSubmit: "return validateEditPassword()") do |f| %>
								<div class="row">
									<div class="col-md-6 col-md-offset-3">
										<div class="page-header">
										  <h3 class="text-center"><i class="fa fa-lock text-danger"></i> <%= getTextMessage("change_password") %> <small>(<%= getTextMessage("required_fields") %> <i class="fa fa-asterisk text-danger"></i>)</small></h3>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div id="edit_user_password_message"></div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-6 col-md-offset-3">
												<i class="fa fa-unlock"></i> <%= f.label :password_old, getTextMessage("current_password") %> <i class="fa fa-asterisk text-danger"></i>
												<%= f.password_field :password_old, class: "form-control", placeholder: getTextMessage("current_password") %>
											</div>
										</div>
										<br>
										<div class="row">
											<div class="col-md-6 col-md-offset-3">
												<i class="fa fa-lock"></i> <%= f.label :password, getTextMessage("new_password") %> <i class="fa fa-asterisk text-danger"></i>
												<%= f.password_field :password, class: "form-control", placeholder: getTextMessage("new_password") %>
											</div>
										</div>
										<br>
										<div class="row">
											<div class="col-md-6 col-md-offset-3">
												<i class="fa fa-lock"></i> <%= f.label :password_confirmation, getTextMessage("confirm_password") %> <i class="fa fa-asterisk text-danger"></i>
												<%= f.password_field :password_confirmation, class: "form-control", placeholder: getTextMessage("confirm_password") %>
											</div>
										</div>
										<br>
										<div class="row">
											<div class="col-md-12 col-md-offset-0" align="center">
												<%= f.submit getTextMessage("change"), class: "btn btn-danger", onclick: "return validateEditPassword()" %>
											</div>
										</div>
									</div>
								</div>
							<% end %>
					  </div>
					</div>
			  </div>
			</div>
		</div>